alertmanager:
  enabled: false
pushgateway:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
